import React from "react";
import { useReferralsTranslations } from "@/hooks/use-referrals-translations";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Clipboard, Share2, Link, Copy, CheckCircle2 } from "lucide-react";
import RankBadge from "./rank-badge";

interface ReferralCodeCardProps {
  referralCode: string;
  onCopy: () => Promise<void>;
  onShare: () => Promise<void>;
  referralCount?: number;
}

/**
 * Componente mejorado para mostrar y compartir el código de referido
 */
const ReferralCodeCard: React.FC<ReferralCodeCardProps> = ({ 
  referralCode, 
  onCopy, 
  onShare,
  referralCount = 0
}) => {
  const rt = useReferralsTranslations();
  const [copied, setCopied] = React.useState(false);
  
  // Crear la URL completa para mostrar
  const referralUrl = `${window.location.origin}/referrals?code=${referralCode}`;
  
  // Función para manejar la copia con feedback visual
  const handleCopy = async () => {
    await onCopy();
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <Card className="overflow-hidden shadow-lg bg-gradient-to-br from-card to-primary/5 border-primary/10">
      <div className="absolute top-0 right-0 w-40 h-40 bg-primary opacity-5 rounded-full filter blur-3xl -translate-y-1/2 translate-x-1/3"></div>
      
      <CardHeader className="flex flex-row items-start justify-between">
        <div>
          <CardTitle className="flex items-center gap-2 text-2xl">
            <Link className="h-5 w-5 text-primary" />
            {rt.shareYourCode}
          </CardTitle>
          <CardDescription>
            {rt.copyReferralLink}
          </CardDescription>
        </div>
        <RankBadge referralCount={referralCount} size="lg" showLabel />
      </CardHeader>
      
      <CardContent className="relative z-10 space-y-6">
        {/* Código de referido */}
        <div className="space-y-2">
          <label className="text-sm font-medium">{rt.personalReferralCode}</label>
          <div className="bg-card border border-primary/20 rounded-lg p-3 flex items-center justify-between">
            <div className="font-mono text-lg">{referralCode}</div>
            <Button
              variant="ghost"
              size="icon"
              onClick={handleCopy}
              className="text-muted-foreground hover:text-primary"
            >
              {copied ? <CheckCircle2 size={18} className="text-emerald-500" /> : <Copy size={18} />}
            </Button>
          </div>
        </div>
        
        {/* URL completa */}
        <div className="space-y-2">
          <label className="text-sm font-medium">{rt.referralProgram}</label>
          <div className="bg-card border border-primary/20 rounded-lg p-3 overflow-hidden">
            <div className="flex items-center gap-2">
              <div className="font-mono text-sm truncate flex-1">
                {referralUrl}
              </div>
              <Button
                variant="ghost"
                size="icon"
                onClick={handleCopy}
                className="flex-shrink-0 text-muted-foreground hover:text-primary"
              >
                {copied ? <CheckCircle2 size={18} className="text-emerald-500" /> : <Copy size={18} />}
              </Button>
            </div>
          </div>
        </div>
        
        {/* Botones de acción */}
        <div className="grid grid-cols-2 gap-4 pt-2">
          <Button 
            variant="outline" 
            className="w-full gap-2 border-primary/20 hover:bg-primary/5" 
            onClick={handleCopy}
          >
            <Clipboard size={16} />
            {rt.copyToClipboard}
          </Button>
          <Button 
            className="w-full gap-2" 
            onClick={onShare}
          >
            <Share2 size={16} />
            {rt.share}
          </Button>
        </div>
        
        {/* Instrucciones */}
        <div className="bg-primary/5 rounded-lg p-4 border border-primary/20 mt-4">
          <h3 className="font-medium text-base mb-2">{rt.stepsToEarn}</h3>
          <ul className="space-y-2 text-sm text-muted-foreground">
            <li className="flex items-start gap-2">
              <span className="bg-primary/10 text-primary w-5 h-5 rounded-full flex items-center justify-center flex-shrink-0 mt-0.5">1</span>
              <span>{rt.codeAutoGenerated}</span>
            </li>
            <li className="flex items-start gap-2">
              <span className="bg-primary/10 text-primary w-5 h-5 rounded-full flex items-center justify-center flex-shrink-0 mt-0.5">2</span>
              <span>{rt.shareWithFriends}</span>
            </li>
            <li className="flex items-start gap-2">
              <span className="bg-primary/10 text-primary w-5 h-5 rounded-full flex items-center justify-center flex-shrink-0 mt-0.5">3</span>
              <span>{rt.earnRewards}</span>
            </li>
          </ul>
        </div>
        
        {/* Incentivo visual - Versión corregida sin animación */}
        <div 
          className="bg-gradient-to-r from-emerald-500/10 to-blue-500/10 rounded-lg p-4 border border-emerald-500/20 text-center"
        >
          <p className="font-medium text-sm">
            {rt.referralAprBoostMessage}
          </p>
        </div>
      </CardContent>
    </Card>
  );
};

export default ReferralCodeCard;